<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.7" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.7" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.7" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CefSharpBrowser.WinForms\CefSharpBrowser.WinForms.csproj"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);NU1702</NoWarn>
  </PropertyGroup>

  <Target Name="CopyChildExe" AfterTargets="Build">
    <ItemGroup>
      <_ChildExe Include="$(ProjectDir)..\CefSharpBrowser.WinForms\bin\$(Platform)\$(Configuration)\net462\CefSharpBrowser.WinForms.exe" />
      <_ChildExe Include="$(ProjectDir)..\CefSharpBrowser.WinForms\bin\$(Configuration)\net462\CefSharpBrowser.WinForms.exe" />
    </ItemGroup>
    <Copy SourceFiles="@(_ChildExe)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" Condition="Exists('%(Identity)')" />
  </Target>
</Project>
