<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
    <RootNamespace>CefSharpBrowser.WinForms</RootNamespace>
    <AssemblyName>CefSharpBrowser.WinForms</AssemblyName>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.WinForms.NETCore" Version="109.1.110" />
  </ItemGroup>
</Project>
